In [8]:
import numpy as np
array_1 = np.array([[0, 1], [2, 3], [4, 5]])
array_2 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
multiplication = np.dot(array_1, array_2)
print(multiplication)
max_multiplication = np.max(multiplication)
print(max_multiplication)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
